# Generated by Django 4.2.8 on 2024-01-04 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AuthorName', models.CharField(max_length=50)),
                ('AuthorDob', models.DateField()),
                ('AuthorGender', models.CharField(max_length=20)),
                ('AuthorEmail', models.CharField(max_length=50)),
                ('AuthorPhone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CityName', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookName', models.CharField(max_length=50)),
                ('BookDescription', models.CharField(max_length=500)),
                ('BookPublishedOn', models.DateField()),
                ('BookPrice', models.IntegerField(default=0)),
                ('BookAuthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookStore.author')),
                ('BookCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookStore.category')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='AuthorCity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookStore.city'),
        ),
    ]
